FileVersion = 1
Dependencies = {corlib = "*", soloud-beef = "*"}

[Project]
Name = "example"
StartupObject = "example.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\..\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\..\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)\\..\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\..\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]
