FileVersion = 1

[Project]
Name = "soloud-beef"
TargetType = "BeefLib"
StartupObject = "soloud_beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\soloudDebug.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)\\.build\\win64_vs2019\\bin\\soloudRelease.lib"]

[Configs.Debug.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libsoloudDebug.a"]
OtherLinkFlags = "$(LinkFlags) -framework CoreServices -framework CoreAudio -framework AudioToolbox"

[Configs.Release.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework CoreServices -framework CoreAudio -framework AudioToolbox"

[Configs.Paranoid.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework CoreServices -framework CoreAudio -framework AudioToolbox"

[Configs.Test.macOS]
LibPaths = ["$(ProjectDir)\\.build\\osx64_clang\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags) -framework CoreServices -framework CoreAudio -framework AudioToolbox"

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libsoloudDebug.a"]
OtherLinkFlags = "$(LinkFlags)"

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags)"

[Configs.Paranoid.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags)"

[Configs.Test.Linux64]
LibPaths = ["$(ProjectDir)\\.build\\linux64_gcc\\bin\\libsoloudRelease.a"]
OtherLinkFlags = "$(LinkFlags)"